version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build and push Docker image"
          command: |
            docker build -t jkzilla.azurecr.io/jkzilla:latest .

workflows:
  workflow1:
    jobs:
      - build
