version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.12
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: false
      - run:
          name: "Build and push Docker image"
          command: |
            # Construir la imagen Docker pasando la variable SECURE_KEY
            docker build --build-arg SECURE_KEY=${SECURE_KEY} -t aocaer4paians.azurecr.io/carpbackend:latest .

workflows:
  workflow1:
    jobs:
      - build
